version: '3.3'
services:
  db:
    container_name: mongodb-container
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  app:
    container_name: auth-api-container
    build: 
      context: .
    ports:
      - "13000:13000"
    depends_on:
      - db